_target_: src.models.sf2m_module.StructureFlowModule
_partial_: true

datamodule: ${data}
T: 5
sigma: 1.0
dt: 0.2
batch_size: 64
alpha: 0.1
reg: 5e-6
correction_reg_strength: 1e-3
n_steps: 15000
lr: 3e-3
device: null
GL_reg: 0.04
knockout_hidden: 100
score_hidden: [100, 100]
correction_hidden: [64, 64]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3e-3
  weight_decay: 1e-2
# model:
#   _target_: src.models.components.sf2m_ngm1.SF2MNGM
#   datamodule: ${data}
#   T: 5
#   sigma: 1.0
#   dt: 0.2
#   batch_size: 64
#   alpha: 0.1
#   reg: 5e-6
#   correction_reg_strength: 1e-3
#   n_steps: 15000
#   lr: 3e-3
#   device: null
#   GL_reg: 0.04
#   knockout_hidden: 100
#   score_hidden: [100, 100]
#   correction_hidden: [64, 64]
# optimizer:
#   _target_: torch.optim.AdamW
#   _partial_: true
#   lr: 3e-3
#   weight_decay: 1e-2

# net:
#   _target_: src.models.components.base.MLPODEFKO
#   dims: [8, 100, 1]
#   GL_reg: 0.04
#   bias: true
#   knockout_masks:
#     _target_: src.models.components.knockoutMasks.KnockoutMaskProvider
#     data_path: data/
#     dataset: dyn-TF
#     dataset_type: Synthetic

# score_net:
#   _target_: src.models.components.cond_mlp.MLP
#   d: 8
#   hidden_sizes: [100,100]
#   time_varying: true
#   conditional: true
#   conditional_dim: 8

# corr_net:
#   _target_: src.models.components.simple_mlp.MLP
#   d: 8
#   hidden_sizes: [64,64]
#   time_varying: true

# partial_solver:
#   _target_: src.models.components.solver.FlowSolver
#   _partial_: true
#   ode_solver: "euler"
#   atol: 1e-5
#   rtol: 1e-5

# # ot_sampler:
# #  _target_: src.models.components.optimal_transport.EntropicOTFM

# sigma: 1.0
# sigma_min: 0.1
# alpha: 0.1
# corr_strength: 1e-3
# reg: 5e-6
# lr: 3e-3
# batch_size: 64
# skip_time: null
# avg_size: -1
# leaveout_timepoint: -1
# test_nfe: 100
# plot: false
# nice_name: "SF2M"
